name: Spaceman
description: |
  Presidio Space Manager Webex Teams Bot
version: v1.0
category: Bots
maintainer: Brad Haas, Jeff Levensailor
license: Presidio Internal Only
projectURL: https://gitlab.presidio.com/jlevensailor/spaceman.git
